# -*- coding: utf-8 -*-
"""movie_recomm-webapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQEGuYYMXX62ezg2xwMfJxgYBhjaKnn2
"""

import numpy as np
import pickle
import pandas as pd

import streamlit as st

from PIL import Image


pickle_in = open("movie_recomm.pkl","rb")
recommendor = pickle.load(pickle_in)


def welcome():
    return "Welcome All"


def recomend_tamil_movies(user_input):

    """
    This will recommend movie based on user input
    """

    recom =recommendor.predict(user_input)

    return recom



def main():
    st.title("Tamil Movies Recommendor")
    html_temp = """
    <div style="background-color:blue;padding:10px">
    <h2 style="color:white;text-align:center;">Streamlit Tamil Movies Recommendor App </h2>
    </div>
    """
    st.markdown(html_temp,unsafe_allow_html=True)
    user_input = st.text_input("Enter the name of your favorite movie: ", "Type Here")

    result=""
    if st.button("recommend"):
        result=recomend_tamil_movies(user_input)
    st.success('Recommending.. {}'.format(result))
    if st.button("About"):
        st.text("Lets LEarn")
        st.text("Built with Streamlit")

if __name__=='__main__':
    main()